# Generated by Django 5.1.3 on 2025-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome/Bootstrap icon class (e.g., 'bi-tree')", max_length=100)),
                ('color', models.CharField(default='primary', help_text="Bootstrap color class (e.g., 'text-success')", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('mpesa', 'Mpesa'), ('paypal', 'PayPal')], max_length=10)),
                ('card_name', models.CharField(blank=True, max_length=150, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=2, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=4, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Bootstrap icon class (e.g., 'bi-hospital')", max_length=100)),
            ],
        ),
    ]
