# Generated by Django 5.1.6 on 2025-03-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicContent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recurringdonation',
            old_name='monthly_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='expiry_year',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='recurringdonation',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recurringdonation',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='recurringdonation',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card')], max_length=10),
        ),
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=255, unique=True)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_transactions', to='PublicContent.donation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
